### ISSUE TITLE
Non-english not supported

### ISSUE THREAD

**Issue by SouljaVR** [mark-rez/TikTok-Voice-TTS#6]
Firstly, thank you for your work! It's been very helpful for getting quick TTS done for a personal project I'm working on; I really appreciate you sharing it with the community. I just had a small question - for some reason it doesn't seem to support non-English characters, though the TikTok API does have support for this with specific voices. e.g the KR voices should support Korean characters etc. Is there anything I can do to fix this? Perhaps I'm just doing something wrong on my end, thank you.

**Comment by mark-rez** [comment]
Non-English languages work on my pc. I have tested Korean (see my code below). Maybe it would be helpful if you explain what exactly you did and what the error message is.

```py
from tiktok_voice import tts, Voice

text = "안녕하세요, 테스트용 오디오입니다."

tts(text, Voice.KR_MALE_1, "output.mp3", play_sound=True)
```

**Comment by SouljaVR** [comment]
You are right, it was an issue on my end with the way I was sending non-english characters. I did print my payload to see if that was the issue initially, but I had made an oversight, apologies and thank you for replying so fast!
